database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "good-user"
  password: "good-password"
  dbname: "order_db"
  sslmode: "disable"
  timeZone: "Asia/Calcutta"
serverConfig: 
  serverPort: 8080