version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: order_processing_system_db
    environment:
      POSTGRES_USER: good-user
      POSTGRES_PASSWORD: good-password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app_network:
